---
- hosts: all
  vars:
    sx5idm_url: http://localhost:18085
    sx5idm_keycloak_enabled: false
    sx5idm_container_name: sx5idm 
    sx5idm_docker_image: nexus3.inspq.qc.ca:5000/inspq/sx5-idm
    sx5idm_external_port: 18085
    sx5idm_internal_port: 8089
  tasks:
  - name: Creation du conteneur pour sx5idm 
    docker_container:
      name: "{{ sx5idm_container_name }}"
      hostname: "{{ sx5idm_container_name }}"
      image: "{{ sx5idm_docker_image }}:{{ sx5idm_image_version }}"
      state: started
      restart_policy: unless-stopped
      ports:
      - "{{ sx5idm_external_port }}:{{ sx5idm_internal_port }}"
  
  - name: Attendre que le serveur idm soit disponible
    uri:
      url: "{{ sx5idm_url }}/idm/config/systemes"
      status_code: 200
      validate_certs: no
    register: result
    until: result.status == 200
    retries: 5
    delay: 10
          
      