---
- hosts: all
  vars:
    sx5habilitationservices_keycloak_enabled: false
    sx5habilitationservices_container_name: sx5habilitationservices 
    sx5habilitationservices_docker_image: nexus3.inspq.qc.ca:5000/inspq/sx5-habilitation-services
    sx5habilitationservices_image_version: latest
    sx5habilitationservices_external_port: 18182
    sx5habilitationservices_internal_port: 8080
    sx5habilitationservices_url: "http://localhost:{{ sx5habilitationservices_external_port }}"
    keycloak_url: http://{{ ansible_hostname }}:18081
  tasks:
  - name: Creation du conteneur pour sx5habilitationservices 
    docker_container:
      name: "{{ sx5habilitationservices_container_name }}"
      hostname: "{{ sx5habilitationservices_container_name }}"
      image: "{{ sx5habilitationservices_docker_image }}:{{ sx5habilitationservices_image_version }}"
      state: started
      restart_policy: unless-stopped
      ports:
      - "{{ sx5habilitationservices_external_port }}:{{ sx5habilitationservices_internal_port }}"
      env:
        "KEYCLOAK_URL": "{{ keycloak_url }}"        
  
  - name: Attendre que le serveur sx5habilitationservices soit disponible
    uri:
      url: "{{ sx5habilitationservices_url }}/config"
      status_code: 200
      validate_certs: no
    register: result
    until: result.status == 200
    retries: 5
    delay: 10
          
      